theme: jekyll-theme-slate

gem "github-pages", group: :jekyll_plugins

title: [Alice's Portfolio]
description: [A Biochemistry student who loves technical problem solving]

url: http://Naliph.github.io
